default_language: "en_US"
features:
  global_list:
    command: globallist
    aliases:
      - glist
      - list
      - players
    progress:
      count: 45
      complete: "|"
      not_complete: "<gray>|"
    server:
      BedWarsMain:
        sum:
          - "bw-server-1"
          - "bw-server-2"
          - "bw-server-3"
      bw-server-1:
        hidden: true
      bw-server-2:
        hidden: true
      bw-server-3:
        hidden: true
    vanish:
      decoration:
        server: "<yellow>$server</yellow>"
        player: "<red>$player</red>"